### ISSUE TITLE
Stopped working following update

### ISSUE THREAD

**Issue by Ooozaboo** [paviro/MMM-Wunderlist#12]
Hi,
MMM-Wunderlist prompted for an update, which I have done, but now it's stopped working.
Original code is still in config.js with my access token and clinet ID, the list names load but the tasks in the lists dont.
I did get the warnings below when running npm install from the module directory:

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN prefer global marked@0.3.6 should be installed with -g

**Comment by paviro** [comment]
@Santanachia wrote the update and it works for me. Any idea?

**Comment by Ooozaboo** [comment]
Since @Mar-85 had a similar issue with the April update where he was having problems loading two lists, I tried removing one of mine and that worked, so I now have the same issue as @Mar-85. One list will load, but adding a another to the config.js causes both of them to fail.

**Comment by Santanachia** [comment]
1. Warnings appears due to dependencies of [wunderlist](https://www.npmjs.com/package/wunderlist) to those old versions and we can't do anything with it. Maybe You'll try to report those warnings at wunderlist's [github](https://github.com/wunderlist/wunderlist.js/issues)?
2. Do You have any other then npm warnings? Anything unusual in console?

**Comment by Mar-85** [comment]
i do remember seeing some npm warnings, but not sure how to get back to seeing where they were. I think in the long term these issues dont really matter anymore as microsoft is shutting down wunderlist sadly.

**Comment by Softyathome** [comment]
I didn't use Wunderlist for a while. Now, after some month, i didn't get any from the list.
I've tried an old copy of MM - but without effect.
Did Wunderlist work for you?
