### ISSUE TITLE
As of the April update only one Wunderlist module works when two are on screen

### ISSUE THREAD

**Issue by Mar-85** [paviro/MMM-Wunderlist#13]
I have two modules showing different lists, and as of the April update only one module works. When i reset the MM whichever module comes up first loads the list then the other just stays blank.

**Comment by paviro** [comment]
@Santanachia  any ideas? Otherwise I will revert your changes for now :/

**Comment by nheobug** [comment]
Hi there,
I'm suffering the same. I mean, when I´ve two modules showing each one his list... doesnt show both, just one... How can we resolve this? Thanks!

**Comment by ArneCL** [comment]
I wrote a fix for this - This error occurs due to missing instance handling in the node_helper. However I wonder if this Project is still being maintained? If so, I'll prepare a PR ASAP ....

**Comment by paviro** [comment]
Not really but I will merge your PR.
