### ISSUE TITLE
Time Format changeable ?

### ISSUE THREAD

**Issue by Beginner88888** [paviro/MMM-Wunderlist#14]
Hi, 

it is possible to change the Time format ?? 
![image](https://cloud.githubusercontent.com/assets/26977067/24803730/666d21c8-1bac-11e7-88e0-8fe3e73975e5.png)
i would like to have dd.mm.yyyy

**Comment by Santanachia** [comment]
ready in #15

**Comment by Beginner88888** [comment]
Works, thanks
