### ISSUE TITLE
Winderlist acess tokken 

### ISSUE THREAD

**Issue by shgmongo** [paviro/MMM-Wunderlist#3]
Hi,

I am a newbie. Need I a Wunderlist tokken to run the module?
Or is a Wunderlist account sufficient?
What is the Job of the tokken?

Regards,

Sebastian

**Comment by paviro** [comment]
Like stated in the README you need an access token to authenticate you. If you need support and are not reporting a bug, please refer to http://forum.magicmirror.builders
