### ISSUE TITLE
Nothing showing up on the module at all

### ISSUE THREAD

**Issue by saml-dev** [paviro/MMM-Wunderlist#4]
I edited `fetcher_debug_client.js` and ran it and this is the only output I got:

```
Create new todo fetcher for list: Inbox - Interval: 1000
```

Any advice? Thanks in advance.

**Comment by Raztou3D** [comment]
Hi,

Nothing's showing up on my screen either. I guess I miss-configured my App on Wunderlist dev page.

What am I supposed to select as "APP URL" and "AUTH CALLBACK URL" ?

Thanks in advance !

**Comment by jwalaszek** [comment]
@Raztou3D 
I've put "http://EXTERNAL_IP_ADDRESS_OF_MY_RASPBERRY" in both fields and now it works fine

**Comment by JoeSpencer** [comment]
I had the same issue and fixed it by generating a new access token

**Comment by paviro** [comment]
Have you resolved this?

**Comment by saml-dev** [comment]
It hasn't worked for me unfortunately. I have a Dynamic DNS service that points to my external IP since my ISP changes it regularly, but setting both of the URLs in my key settings on Wunderlist to that URL didn't work.

**Comment by JoeSpencer** [comment]
@paviro My setup has been working for a while and it functions well!

for me it was generating a new token

**Comment by saml-dev** [comment]
Wow. Just revisited this and realized I was using the client secret instead of the access token. I didn't see the create token button there. Dumb mistake lol.
