### ISSUE TITLE
Stop Syncing

### ISSUE THREAD

**Issue by JonaZz747** [paviro/MMM-Wunderlist#7]
After some time the Modul stops syncing with my Wunderlist. When a add or remove anything the modul is syncing it first but when I add/remove anything after some hours the Modul doesen't syncs it. When I restart my Mirror it is working again. I'm using a RPi 3 with Raspbian and latest Packages, Magic Mirror version and npm programs.

**Comment by Ooozaboo** [comment]
I had the same issue, I changed the refresh time to every 10 minutes and its working fine now.

**Comment by JonaZz747** [comment]
Thanks, with that it is working for me too

**Comment by mirko3000** [comment]
I have the same issue, increasing the refresh time to 5 min still did not solve the problem. Any other idea?

**Comment by paviro** [comment]
Have you updated to the latest version?

**Comment by mirko3000** [comment]
I thought I did - but apperently I did it wrong ;-) Now it works like a charm, thanks!
