### ISSUE TITLE
missing assignee and due date

### ISSUE THREAD

**Issue by Santanachia** [paviro/MMM-Wunderlist#8]
Hi,
could you add two new columns to the tasks list?
I'm sharing "ToDo" list and it's hard to distinguish which tasks are mine.
example how could it look like:
<table>
<thead><tr><th>deadline</th><th>task</th><th>assignee</th></tr></thead>
<tbody>
<tr><td>yesterday</td><td>build MagicMirror</td><td>M</td></tr>
<tr><td>today</td><td>install soft</td><td></td></tr>
<tr><td>tomorrow</td><td>start all over again</td><td>K</td></tr>
</tbody>
</table>

**Comment by PatrickGlatz** [comment]
Hello, I also would like to see something like this and, if possible, a specific icon in front of every entry to which list it belongs. I really love giving the lists as array. That is very useful.

**Comment by Santanachia** [comment]
I've added the possibility to show those columns, but first i need changes from #10
