### ISSUE TITLE
Wunderlist.js SDK

### ISSUE THREAD

**Issue by Santanachia** [paviro/MMM-Wunderlist#9]
Why not to use [Wunderlist.js SDK](https://developer.wunderlist.com/documentation/tools/wunderlist.js) instead of [request](https://www.npmjs.com/package/request)?

**Comment by paviro** [comment]
Not sure if it hasn't exist back then or if it did not work for some reason. Anyway feel free to send a pull request!

**Comment by Santanachia** [comment]
I've send You a pull request

**Comment by Santanachia** [comment]
I've send You a pull request #10
